/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Copy, ImagePlus, UploadCloud } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

type Media = { name: string; id: string; created_at: string; metadata: { size?: number; mimetype?: string } | null };
export default function AdminMediaPage(){const db=createSupabaseBrowserClient();const [items,setItems]=useState<Media[]>([]);const [notice,setNotice]=useState("");async function load(){const {data,error}=await db.storage.from("public-media").list("",{limit:100,sortBy:{column:"created_at",order:"desc"}});if(error)setNotice("Could not load media library.");else setItems((data||[]) as Media[])}useEffect(()=>{load()},[]);async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const path=`${crypto.randomUUID()}-${file.name}`;const {error}=await db.storage.from("public-media").upload(path,file,{upsert:false});setNotice(error?"Upload failed.":"Media uploaded.");if(!error)load();e.target.value=""}function copy(name:string){const url=`${window.location.origin}/storage/v1/object/public/public-media/${name}`;navigator.clipboard.writeText(url);setNotice("Public URL copied.")}return <main className="min-h-screen bg-[#f3f2ee] text-[#171717]"><header className="border-b border-black/10 bg-[#171717] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-white/70"><ArrowLeft className="h-4 w-4"/> Admin control room</Link><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#d9ff53] px-4 py-2 text-sm font-black text-[#171717]"><UploadCloud className="h-4 w-4"/> Upload<input type="file" accept="image/*" onChange={upload} className="sr-only"/></label></div></header><div className="mx-auto max-w-7xl px-5 py-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-black/45">Website assets</p><h1 className="mt-2 text-4xl font-black">Media library</h1>{notice&&<p className="mt-4 rounded-xl bg-white px-4 py-3 text-sm font-bold">{notice}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{items.length?items.map(item=><article key={item.id} className="overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="flex aspect-square items-center justify-center bg-[#f8f7f4]"><ImagePlus className="h-8 w-8 text-black/25"/></div><div className="p-4"><p className="truncate text-sm font-bold">{item.name}</p><button onClick={()=>copy(item.name)} className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-black/55"><Copy className="h-3.5 w-3.5"/> Copy public URL</button></div></article>):<div className="rounded-2xl border border-dashed border-black/20 bg-white p-12 text-center text-sm text-black/55 sm:col-span-2 lg:col-span-4">No public media uploaded yet.</div>}</div></div></main>}
