import { redirect } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, FilePlus2 } from "lucide-react";
import { getSupabaseServerClient } from "@/lib/supabase/server";

export default async function DashboardQuotesPage() {
  const supabase = await getSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/portal/login");
  const { data: quotes } = await supabase.from("quotes").select("id, quote_number, service, status, price, estimated_delivery, created_at").eq("client_id", user.id).order("created_at", { ascending: false });
  const labels: Record<string, string> = { new: "New", reviewing: "Under review", quoted: "Quote sent", client_questions: "Question sent", accepted: "Accepted", rejected: "Rejected", converted: "Converted", expired: "Expired" };
  return <main className="min-h-screen bg-[#f3f2ee] text-[#171717]"><header className="border-b border-black/10 bg-[#171717] text-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/portal" className="inline-flex items-center gap-2 text-sm font-bold text-white/70 hover:text-white"><ArrowLeft className="h-4 w-4" /> Dashboard</Link><Link href="/quote" className="inline-flex items-center gap-2 rounded-xl bg-[#d9ff53] px-4 py-2.5 text-sm font-black text-[#171717]"><FilePlus2 className="h-4 w-4" /> Request quote</Link></div></header><div className="mx-auto max-w-6xl px-5 py-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-black/45">Commercial workspace</p><h1 className="mt-2 text-4xl font-black">Your quotes</h1><div className="mt-8 overflow-hidden rounded-2xl border border-black/10 bg-white">{quotes?.length ? quotes.map((quote) => <div key={quote.id} className="grid gap-4 border-b border-black/8 px-5 py-5 last:border-0 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-black/45">{quote.quote_number}</p><h2 className="mt-1 font-black">{quote.service}</h2><p className="mt-1 text-sm text-black/55">Submitted {new Date(quote.created_at).toLocaleDateString()}</p></div><div className="text-left sm:text-right"><span className="rounded-full bg-[#eef0e9] px-3 py-1 text-xs font-bold">{labels[quote.status] || quote.status}</span><p className="mt-2 text-sm font-bold">{quote.price !== null ? `$${quote.price}` : "Pricing pending"}</p></div></div>) : <div className="p-12 text-center"><p className="font-bold">No quote requests yet.</p><p className="mt-2 text-sm text-black/55">Start with your artwork brief and we will respond in the portal.</p><Link href="/quote" className="mt-5 inline-flex rounded-xl bg-[#171717] px-4 py-3 text-sm font-bold text-white">Request your first quote</Link></div>}</div></div></main>;
}
